#!/bin/bash
set -euo pipefail

#TMPFILE=‘mktemp -t example.XXXXXXXXXX‘ || exit 1
#cleanup() {
#    rm -rf "$TMPFILE"
#}
#trap cleanup EXIT

version=$1

wget "https://github.com/michaelszymczak/Chronicle-Queue/archive/chronicle-queue-${version}.tar.gz"
tar -xzvf "chronicle-queue-${version}.tar.gz"
cd "Chronicle-Queue-chronicle-queue-${version}" && mvn -Dmaven.test.skip=true clean install